# Nigeria Premier Football League (NPFL) Standings Analysis

## Objective
Scraping real NPFL league table data from the official NPFL website
to derive performance metrics and insights.

In [18]:
# explanation:
# We use requests to fetch HTML, BeautifulSoup to parse it,
# and pandas to organize and clean the data we scrape.

import requests
from bs4 import BeautifulSoup
import pandas as pd

In [44]:
# explanation: I keep getting 403; i.e., the website is blocking my request, so I had to use the workaround below.
# Some websites block simple bot requests, so we include a headers
# string to pretend to be a real browser visiting the page.


headers = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/120.0 Safari/537.36"
    )
}

url = "https://npfl.com.ng/npfl-table/"
response = requests.get(url, headers=headers)

response.status_code

200

In [45]:
# explanation:
# BeautifulSoup turns the raw HTML into a navigable structure
# so we can find the league table easily.


soup = BeautifulSoup(response.text, "html.parser")

In [46]:
# explanation:
# The standings table is the first <table> on this page.


table = soup.find("table")

In [47]:
# explanation:
# Headers like Pos, Club, P, W, D, L, F, A, GD, Pts


headers = [th.text.strip() for th in table.find_all("th")]
headers

['Pos', 'Club', 'P', 'W', 'D', 'L', 'F', 'A', 'GD', 'Pts']

In [52]:
# explanation:
# Loop through the table rows to pull team performance data.


rows = table.find_all("tr")[1:]
data = []

for row in rows:
    cells = row.find_all("td")
    if len(cells) == 0:
        continue
    row_data = [cell.text.strip() for cell in cells]
    data.append(row_data)

data[:5]

[['1',
  'Rangers International FC',
  '28',
  '13',
  '8',
  '7',
  '32',
  '20',
  '12',
  '47'],
 ['2', 'Rivers United FC', '25', '12', '10', '3', '21', '14', '7', '46'],
 ['3', 'Ikorodu City FC', '28', '12', '9', '7', '26', '20', '6', '45'],
 ['4', 'Nasarawa United FC', '28', '12', '8', '8', '25', '22', '3', '44'],
 ['5', 'Abia Warriors FC', '28', '12', '7', '9', '22', '20', '2', '43']]

In [53]:
# explanation:
# Convert the scraped table into a pandas DataFrame so we can
# clean and analyze it like a spreadsheet.

df = pd.DataFrame(data, columns=headers)
df.head()

  Pos                      Club   P   W   D  L   F   A  GD Pts
0   1  Rangers International FC  28  13   8  7  32  20  12  47
1   2          Rivers United FC  25  12  10  3  21  14   7  46
2   3           Ikorodu City FC  28  12   9  7  26  20   6  45
3   4        Nasarawa United FC  28  12   8  8  25  22   3  44
4   5          Abia Warriors FC  28  12   7  9  22  20   2  43

In [54]:
# explanation:
# Convert the numeric columns to integers so we can calculate
# metrics like Win Percentage.


numeric_cols = ["P", "W", "D", "L", "F", "A", "GD", "Pts"]

# so we are doing that with this code 

for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

df["Win_Percentage"] = round((df["W"] / df["P"]) * 100, 2)
df.head()

,Pos,Club,P,W,D,L,F,A,GD,Pts,Win_Percentage
0,1,Rangers International FC,28,13,8,7,32,20,12,47,46.43
1,2,Rivers United FC,25,12,10,3,21,14,7,46,48.00
2,3,Ikorodu City FC,28,12,9,7,26,20,6,45,42.86
3,4,Nasarawa United FC,28,12,8,8,25,22,3,44,42.86
4,5,Abia Warriors FC,28,12,7,9,22,20,2,43,42.86

In [56]:
# explanation:
# I had to use my PC's full path to ensure the CSV file is saved
# where I can easily access it. On my computer, this is:
# C:\Users\USER\Documents\Python files


df.to_csv(r"C:\Users\USER\Documents\Python files\npfl_standings_2025.csv", index=False)

In [57]:
# explanation:
# Sort by Win Percentage from highest to lowest and display
# the top performing teams.
df.sort_values(by="Win_Percentage", ascending=False).head(5)

,Pos,Club,P,W,D,L,F,A,GD,Pts,Win_Percentage
1,2,Rivers United FC,25,12,10,3,21,14,7,46,48.00
0,1,Rangers International FC,28,13,8,7,32,20,12,47,46.43
7,8,El-Kanemi Warriors FC,27,12,5,10,25,26,-1,41,44.44
6,7,Shooting Stars Sports Club (3SC),27,12,5,10,27,28,-1,41,44.44
2,3,Ikorodu City FC,28,12,9,7,26,20,6,45,42.86

## Business Insight Summary

Analyzing the NPFL standings shows team performance efficiencies
based on wins, draws, and losses. 

Win percentage is a key metric
for assessing consistency across a season. 

This insight can support
club strategy, sponsorship value assessment, and fan engagement trends.